#!/bin/bash -l

# Variables for filename format
IDENT="$(whoami).$$.$(date --date="today" "+%Y-%m-%d_%H-%M-%S")"
LOG="${IDENT}${TICKET}.json"

# Asciinema binary
ASCIINEMA="/bin/asciinema"

# Hack for SHELL environment variable
export SHELL=/bin/bash

# Disclaimer
echo -e "\n
###############################################################
#                \e[92mAuthorized access only!\e[39m                      #          
# \e[31mDisconnect IMMEDIATELY if you are not an authorized user!!!\e[39m #
#         \e[92mAll actions Will be monitored and recorded\e[39m          #
###############################################################"

# Read ticket number for support purpose
read -p "Please enter ticket number: " TICKET
if [ -z ${TICKET} ]
then
    exit 1
fi

# execute terminal session
${ASCIINEMA} rec -q  /var/log/remote-sessions/${LOG}

echo "Finish"
